#!/bin/bash

cpp_files=(
    "LineAlgorithms.cpp"
    "main.cpp"
)

output_file="output.exe"

compile_run_command="x86_64-w64-mingw32-g++ -mwindows -lgdi32 -static ${cpp_files[*]} -o $output_file"

run_command="wine64 $output_file"

$compile_run_command &&  $run_command  && rm $output_file 
